---
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: Compile NGINX
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu:22.04
          - ubuntu:24.04
          - debian:11
          - debian:12
        nginx_ver:
          - STABLE
          - MAINLINE
        install_type:
          - LIGHT
          - FULL
        ssl:
          - SYSTEM
          - OPENSSL
          - LIBRESSL
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Build NGINX in Docker
        continue-on-error: true
        run: docker build . --file .github/workflows/docker/Dockerfile --build-arg NGINX_VER=${{ matrix.nginx_ver }} --build-arg BASE_IMAGE=${{ matrix.os }} --build-arg INSTALL_TYPE=${{ matrix.install_type }} --build-arg SSL=${{ matrix.ssl }}